disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - vertical_whitespace
  - line_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage