language: objective-c
osx_image: xcode7.2
script:
- xctool -project AppliverySDK.xcodeproj -scheme Applivery build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
notifications:
  slack: applivery:KX1jJ5dWdGbw0xXOXImfKgSD
after_success:
- bash <(curl -s https://codecov.io/bash)
