osx_image: xcode8
language: swift
install:
  - ./script/install_swiftlint.sh
xcode_project: AppliverySDK.xcodeproj
xcode_scheme: Applivery
script:
  - xcodebuild -version
  - xcodebuild -project AppliverySDK.xcodeproj -scheme Applivery -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: applivery:KX1jJ5dWdGbw0xXOXImfKgSD#ci
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'AppliverySDK'
