language: objective-c
osx_image: xcode7.2
xcode_project: AppliverySDK.xcodeproj
xcode_scheme: Applivery
xcode_sdk: iphonesimulator9.2
notifications:
  slack: applivery:KX1jJ5dWdGbw0xXOXImfKgSD
after_success:
- bash <(curl -s https://codecov.io/bash)
