language: objective-c
osx_image: xcode8.2

script:
  - carthage bootstrap --no-use-binaries --platform iOS
  - xcodebuild -project AppliverySDK.xcodeproj -scheme Applivery -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.1,name=iPhone 6" test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: applivery:KX1jJ5dWdGbw0xXOXImfKgSD#ci
