codecov:
  branch: master

comment:
  layout: header, changes, diff, sunburst

coverage:
  precision: 2
  round: down
  range: "30...70"
  ignore:
    - Pods/**
    - Applications/Xcode.app/**
    - vendor/**
    - Carthage/**
    - build/**
    - AppliverySDKTests/**
    - AppliveryBehaviorTests/**
  notify:
    slack:
      default:
        url: https://hooks.slack.com/services/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
        branches:
          - master
          - develop
        threshold: null
        attachments: "sunburst, diff"
  status:
    patch: false
